development:
  adapter: mysql2
  encoding: utf8
  database: incumbent-api-endpoint_development
  pool: 5
  username: root
  password: 12345678

test:
  adapter: mysql2
  encoding: utf8
  database: incumbent-api-endpoint_test
  pool: 5
  username: root
  password: 12345678

production:
  adapter: mysql2
  encoding: utf8
  database: incumbent-api-endpoint_production
  pool: 5
  username: root
  password: 12345678